### ISSUE TITLE
Sign sent BLE data sent with tag ID

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#111]
Depends on #110, gateway data should be signed with device ID somehow. For example if data sent as JSON is 
```
{
  "data": {
    "coordinates":  "",
    "timestamp":  1595504641,
    "gwmac":  "240ac4e32eb4",
    "tags": {. . .
    }
  }
}
```
the signed data could be
```
{
  "data": {
    "coordinates":  "",
    "timestamp":  1595504641,
    "gwmac":  "240ac4e32eb4",
    "tags": {. . .
    }
  },
  "signature":$SIGNATURE
}
```
where value of signature is SHA256(data, device_id).

The goal is to prevent data spoofing.

**Comment by Muhwu** [comment]
For the placement of the signature, I would recommend putting it in a header of choice. It also makes verification simpler because in order to put it in the payload, we'd have to change the payload after calculating the signature (and do the same operation upon receiving).

Modeling from OAuth 1.0a, one could also put a timestamp on the signature that could be verified against - this would limit the time a stolen request could be re-sent - and for that duration, the nonce makes sure that the same request is not sent multiple times. In short, the body from which the signature is hashed could looks something like:
```
<device id+deviceaddr><random nonce><unix timestamp><json body of the message>
```
The headers or the message would then have to include at least the following:
* Timestamp (used to sign the request)
* Nonce (https://tools.ietf.org/html/rfc5849#section-3.3 - good idea to have even if it is not enforced initially)
* Calculated signature
* Some way of identifying the gateway

Since the idea is that the recipient can confirm the authenticity, the last point is important - whether it is a Mac address to device id mapping on the network side or something else.

**Comment by TheSomeMan** [comment]
Since device id and deviceaddr can be easily read by an attacker (and the used algorithm is known), 
these values are not enough to protect from spoofing.
A better way is to add a secret 'salt' (unique for each gateway):
signature := SHA256(data, random nounce, timestamp, device id, device addr, salt)
This 'salt' can be obtained from the Ruuvi server via HTTPS during the gateway activation stage.
To protect 'salt' the flash memory on ESP32 must be encrypted, 
so that no one can read it from the flash memory and installation of unsigned firmware must be prohibited (otherwise modified firmware can print 'salt' to UART).

But there's still a weak point - an attacker can flash the gateway with custom firmware and activate it using Ruuvi server.
To protect from this attack, initial activation should be done on the gateway production stage,
so that the private salt/key is saved to the internal protected storage.
After that users can update firmware using only signed (and optionally encrypted) firmware images.

If someone will build and flash firmware from the source code, then the private activation key/salt will be erased.
This might be a problem since the user will not be able to reactivate the gateway unless he saves whole encrypted content of the flash memory.

**Comment by ojousima** [comment]
> To protect from this attack, initial activation should be done on the gateway production stage,
so that the private salt/key is saved to the internal protected storage.
After that users can update firmware using only signed (and optionally encrypted) firmware images.

I can see how this would make the firmware more secure, on the other hand having a protected key required to access the backend would be against the open-source philosophy of the project. If someone decides to spoof data for themselves, that's not really a problem for Ruuvi or other users. 

The signing is there to protect users from spoofing each other's gateways, do you see an attack where someone without physical access to gateway could spoof the proposed signature?

**Comment by Muhwu** [comment]
It should be noted that the idea is to not necessarily send both device id and addr (my understanding is that these are unique on the device), but one which can be used to identify the device - but not enough to form the entire key. I don't, on principle, oppose registering the salt on gateway activation, but it does bring up the point of "what if it needs to be reset" as was pointed out.

Anyway, if we only send the gateway id, but not other info that only exist on the gateway and the receiving end - then, it should provide a reasonable protection against spoofing. In other words, we needn't include the device addr in the payload, just make it part of the encrypted hash. The receiving backend will construct it's own version of the hash, checking against the stored device identification information on the server.

I agree that randomly generating a key on the first activation adds security, but then we also need to solve for re-flashing not being equivalent of a bricking the device.

**Comment by Muhwu** [comment]
One more note to add here, the actual hash should not be just just a `sha256` or `sha512` hash of the hashable payload, but we should use a HMAC that uses one of the above. Anyway, I will write an example implementation.
