### ISSUE TITLE
Configuring GW from the local network disconnects from the current (local) network

### ISSUE THREAD

**Issue by io53** [ruuvi/ruuvi.gateway_esp.c#317]
When setting up the gateway via hotspot successfully (custom server, with lan access, ethernet DHCP) and then connect to gateway IP, the Configuration wizard is shown again.
If you try to configure it fails when setting ethernet DHCP and the gateway is no longer accessible from ethernet.

**Comment by io53** [comment]
When you try to configure it again from the local network you need to configure the network settings, and that disconnects from the current network (tested with wifi this time). Leaving you without access to the gateway. I would assume that when the gateway is setup and used from local network you should not get to the configurator 🤔.

**Comment by ojousima** [comment]
>  I would assume that when the gateway is setup and used from local network you should not get to the configurator 🤔.

It would make sense. Updated title and marked this as 1.9 task

**Comment by TheSomeMan** [comment]
I propose to prohibit the ability to change the type of network connection when accessing from LAN:

![image](https://user-images.githubusercontent.com/4346875/132452820-de554a3f-5dc4-41c4-9808-4a8fa561b47e.png)

**Comment by ojousima** [comment]
There should be also a message about why the selection is disabled so users won't get confused, e.g. "LAN access detected, network configuration is disabled. Press Gateway button and connect to the Gateway hotspot to reconfigure the network connection"

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/132629290-dd2f6b79-c4c4-40e6-8ac8-82df4dc120ee.png)

**Comment by laurijamsa** [comment]
Let's don't use this blue colour here as it doesn't fit with the layout and Ruuvi's brand colours. Black bolded left-aligned text would work ok.

Describe also better what to do:

"**You're accessing the Ruuvi Gateway configuration wizard from your local area network. For this reason, you cannot adjust the connection type. In order to change the connection type, please reconfigure the Gateway using its Wi-Fi hotspot. To start the hotspot, press the small configuration button for a short time, found under the power socket.**

**Next, connect to a Wi-Fi hotspot named RuuviGatewayXXXX using a password 12345678. After connecting to the hotspot, your device may ask you to sign in to the network. Next, a new browser window with the correct configuration page will open automatically. But if not, open your web browser and type 10.10.0.1**"

In Finnish:

"**Olet avannut Ruuvi Gatewayn konfigurointisivun lähiverkosta käsin ja tämän takia et voi vaihtaa tapaa kuinka Gateway on yhteydessä internetiin. Voit vaihtaa yhteystyyppiä Gatewayn Wi-Fi-yhteyspisteen kautta. Käynnistääksesi konfigurointi, paina lyhyesti virtaliittimen alla sijaitsevaa nappia.**

**Tämän jälkeen yhdistä uuteen ilmestyneeseen Wi-Fi-verkkoon RuuviGatewayXXXX käyttäen salasanaa 12345678. Seuraavaksi Gatewayn asetussivu aukeaa uuteen selainikkunaan. Jos ikkuna ei aukea, voit avata asetussivun kirjoittamalla selaimesi osoitekenttään osoitteen 10.10.0.1**"

**Comment by TheSomeMan** [comment]
@laurijamsa please check if these page look good now:

![image](https://user-images.githubusercontent.com/4346875/132668203-70876c08-a198-4c22-81b2-1f49b8e7f7d9.png)

![image](https://user-images.githubusercontent.com/4346875/132668265-d3e55416-59e8-4ab8-84f2-4032156df990.png)

**Comment by laurijamsa** [comment]
Looks ok. Thanks.

**Comment by laurijamsa** [comment]
![Screenshot_20210909-132054_Gmail.jpg](https://user-images.githubusercontent.com/1311912/132668954-7399bcc9-4d8a-4390-ae0d-273900883215.jpg)

A copypaste error here

**Comment by TheSomeMan** [comment]
thanks, fixed:
![image](https://user-images.githubusercontent.com/4346875/132669277-ea543bb6-acc9-4124-8f24-179f08cc4cf4.png)

**Comment by markoaamunkajo** [comment]
Added some more fluid Finnish strings, otherwise moving to done
