### ISSUE TITLE
If user is a non-beta tester, first update happens still after 40 minutes

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#337]
[mokkilogi_standard-update-interval.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7072201/mokkilogi_standard-update-interval.txt)

EDIT: Reproduced this one with my second Gateway. Full erase -> flash the latest zip -> power off -> connect ethernet -> power on -> wait 40min -> boom

**Comment by TheSomeMan** [comment]
it's because of test build with reduced delay - 1 hour instead of 2 weeks

First check for fw updates is performed after 40 minutes since reboot:
```
I (2402811) ruuvi_gateway: [main] Check for fw updates: configured weekdays: Sun Mon Tue Wed Thu Fri Sat, current: Sun
I (2402811) ruuvi_gateway: [main] Check for fw updates: configured range [00:00 .. 24:00], current time: 11:39)
I (2402822) ruuvi_gateway: [main] Check for fw updates: activate
```

then it checks how much time has passed since the release was published:
```
I (2406605) http_server: [http_server] github_latest_release.json: tag_name: v1.8.0
I (2406613) http_server: [http_server] github_latest_release.json: Update is required (current version: v1.7.0-2-gc407a70-dirty, latest version: v1.8.0)
I (2406627) http_server: [http_server] github_latest_release.json: published_at: 2021-08-27T16:14:59Z
I (2406637) http_server: [http_server] github_latest_release.json: Run firmware auto-updating from URL: https://github.com/ruuvi/ruuvi.gateway_esp.c/releases/download/v1.8.0
```

It was published 2021-08-27T16:14:59Z, more then 1 hour elapsed since that moment, so auto-updating was activated.
