### ISSUE TITLE
Update configuration mechanism - Encrypt hotspot data

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#456]
Current configuration mechanism has security and usability issues:

* Attacker can record all WiFi traffic in the area and crack user configuration (which includes user home WiFi) if credentials are entered over WiFi hotspot
* Updating large installations is cumbersome because each Gateway has to be configured manually.

To fix these issues, following things should be done:

* Allow Gateway to fetch a configuration .json file from a preconfigured server. By default this is empty field, add URL to fetch configuration from to under Gateway Update page.
* Encrypt configuration posted to Gateway HTTP Server using asymmetric cryptography. Details such as is RSA or Diffie-Hellman used and which exact libraries are used are to be discussed.
* Add CRC32 of configuration to Gateway statistics and under /metrics endpoint. 

See also #455

**Comment by Scrin** [comment]
- I'd suggest including an identifier of some sorts, perhaps the mac address, with the "config pull" to allow a "centralized update server" to distinguish the gateways from each other so that it's possible to serve different configs for different gateways in case different configs are needed, or an incremental config update rollout is desired. Perhaps a custom http header.
- The "config pull" should probably have some sort of auth support, perhaps even just basic auth or a bearer token, to allow securing the update server against unauthorized callers trying to fetch a config that can include secrets.
- Configuring a fixed address to pull config updates from does not mitigate the threat of ARP poisoning (if an IP is used) or DNS cache poisoning (if a hostname is used) or any other MITM type attacks that can allow an attacker to impersonate the update server. Although using https with a cert signed by a CA will mostly mitigate this issue (if the GW validates the https certificates, does is? and if so, how are the CA's updated?)
- Should the "config pull" method support asymmetrically encrypted configs as well? (or did you mean that by the 2nd last point?)

**Comment by TheSomeMan** [comment]
I'm going to use the following crypto-libraries:
* https://github.com/crypto-browserify/diffie-hellman on the browser side
* {ESP_IDF}/components/mbedtls (https://github.com/ARMmbed/mbedtls) for the gateway side

**Comment by ojousima** [comment]
Splitting this task into two different parts:
* Encrypting hotspot (here)
* JSON configuration file (#475)

**Comment by ojousima** [comment]
Since the data is encrypted on application level, hotspot encryption can be left blank.
