### ISSUE TITLE
Support user SSL certs

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#476]
Users should be able to upload their self-signed cert to the gateway. The cert should also be updatable with the remote configuration.

**Comment by hlounent** [comment]
X.509 client certificate would be great for authenticating to MQTT server.

I have an MQTT server that forwards data to an InfluxDB instance (and to Grafana from there) but I've currently only enabled client certificate authentication for security reasons and would prefer not to enable password authentication. Client certificates are more secure especially if the CA used for issuing them is stored in an offline system not connected to Internet.

The client should support sending a certificate chain that contains the end-entity client certificate itself and any intermediate CA certificates in order to establish the chain of trust to the CA certificate that the server uses as its trust anchor.

**Comment by markoaamunkajo** [comment]
Recheck once more with Otso

**Comment by ojousima** [comment]
What is needed to be rechecked?

**Comment by ojousima** [comment]
@TheSomeMan is it possible to fetch the certificate with remote configuration? If not, let's assign that feature to backlog and mark this issue as finished.

**Comment by TheSomeMan** [comment]
> is it possible to fetch the certificate with remote configuration? If not, let's assign that feature to backlog and mark this issue as finished.

Yes, client and server certificate checking is supported for the remote configuration.

**Comment by ojousima** [comment]
>> is it possible to fetch the certificate with remote configuration? If not, let's assign that feature to backlog and mark this issue as finished.

> Yes, client and server certificate checking is supported for the remote configuration.

I meant is it possible to fetch the certificate itself from a remote source instead of upload over LAN?

**Comment by TheSomeMan** [comment]
> I meant is it possible to fetch the certificate itself from a remote source instead of upload over LAN?

Yes, it can be implemented, but let's schedule it for v1.15

**Comment by markoaamunkajo** [comment]
@ojousima could you please test SSL's one more time, just to make sure

**Comment by ojousima** [comment]
Changes: 
- Support TLS v1.3 if feasible
- Re-enable check after uploading certificate file
- Support .crt for certificate and .key for private key

**Comment by markoaamunkajo** [comment]
This task is completed
