### ISSUE TITLE
Add CRC32/SHA256 for ruuvi.json to /metrics API

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#513]

**Comment by Scrin** [comment]
@TheSomeMan please note that the values for metrics are parsed as float64 (see the note near the beginning of metrics.c, which points to: https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md):

- The metrics values are parsed as float64, and thus SHA256 would be too large and end up rounded (crc32 is fine)
- The parsing requires the values to be in a supported format, and `0xaabbccdd` is not one of them

I would recommend leaving SHA256 out entirely and just keep crc32, converted into base10 (instead of hexadecimal). If SHA256 is strictly required here, it should be a label instead to avoid truncation. If you have any questions regarding these, I'm happy to help as I have plenty of experience with this format itself and monitoring tools supporting this format

**Comment by TheSomeMan** [comment]
@Scrin I made the changes you asked for

**Comment by Scrin** [comment]
Thanks. Looking at the latest changes it looks good now

**Comment by markoaamunkajo** [comment]
QA passed
