### ISSUE TITLE
Green LED control by ESP32, use of green and red LEDs to indicate the status of gateway

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#654]
"because we're not going to modify the hardware so that ESP could control the green led, ESP needs to tell nRF when all is good (cloud returned ok) and otherwise keep the green off all the time. but nRF should keep the led on after boot for 5 second before turning it off."

**Comment by ojousima** [comment]
Led codes:

- Solid green, everything ok
- Internet working, but 1 / N backends not working, green 90 % duty cycle
- Configuration hotspot on 50 % 1 / Hz red
- "Nothing" working, solid red

**Comment by ojousima** [comment]
Also, let's check raising UART speed and check waveforms with oscilloscope

**Comment by laurijamsa** [comment]
Documentation https://docs.ruuvi.com/ruuvi-gateway-firmware/gw-getting-started says:


"The green LED is on when receiving data from the Bluetooth sensors is working properly.  "
(this is not correct as also internet & backend has to work to show solid green)

It also says:

Red LED blinks as follows:
5 times/second: Problem with the Internet connection.
2 times/second: Reset to factory settings complete, you can release the button to enter configuration mode.
1 time/second: Internal firmware update. Wait until the blinking stops. This may take up to 10 minutes.
1 time per 2 seconds: Configuration mode, connect to the Gateway's WiFi hotspot to configure.

(these are fine afaik)

**Comment by laurijamsa** [comment]
Gateway schema: https://github.com/ruuvi/gateway_hw

The bus (pins 1-4) between nRF and ESP don't have any series resistors so it may be hard to measure the waveforms. But if your hand is steady enough, possible :)

**Comment by laurijamsa** [comment]
nRF:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/1311912/199431500-544791f5-6f7a-43c1-8c0c-a5293f2370d8.png">

ESP:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1311912/199431565-e03e88dd-67ec-4881-b7a7-140e0cb6b09f.png">

Orientation on the above screenshots is this:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/1311912/199431631-cae5cec9-8be5-4d47-8265-2eea9bb07d9e.png">

**Comment by TheSomeMan** [comment]
I propose changing the indication mode for "Configuration mode" from "RRRRRRRRRR---------" to "RRRRRRRRRRGGGGGGGGGG" (Red/Green switching once per second) because it's a little confusing when only the red LED blinks, it looks like an error.
Currently following indication modes are implemented:
* All good: solid green
* WiFI hotspot active: "RRRRRRRRRRGGGGGGGGGG"
* No network connection: "R-R-R-R-R-"
* Connected to network, but there is no connection to any server (HTTP/MQTT): "RRRRR-----"
* There is no connection to some servers: "GGGGGGGGG-"
* Connected to network, but no data from Bluetooth sensors: "G-G-G-G-G-"
* Flashing firmware on nRF52: "R---------"
* Configuration has been erased by the Configure button: "RR--RR--"

**Comment by ojousima** [comment]
@laurijamsa @markoaamunkajo ^ Please check above UI change

**Comment by laurijamsa** [comment]
Ok, let's do it, I don't have better suggestions right now.

**Comment by markoaamunkajo** [comment]
QA passed
