### ISSUE TITLE
Check how fast bit speed nrf52 is flashed via swd by esp32

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#734]

**Comment by markoaamunkajo** [comment]
Check signal with oscilloscope, to prevent bit errors.

**Comment by TheSomeMan** [comment]
nRF52 is flashed using transactions to write each 32-bit word. To perform SWD transactions at the hardware layer, GPIO is configured for SPI mode, operating at 2 MHz.
 Although SPI bus speed is 2 MHz = 250 kb/sec, the effective write speed is about 1 kb/sec due to big gaps between transactions.

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/87326b54-f7c1-4b1f-80e4-60ac663716fd)
 
![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/38e34509-a9d2-41d2-a8ed-d2b0c9d3e8be)

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/1d782fb6-c734-4c72-8c94-31dc08e5c42c)

**Comment by markoaamunkajo** [comment]
Nothing to QA, moving to done.
