### ISSUE TITLE
Feature: Backend check / validation

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#92]
Warn user about malformed URL, leading / trailing slash in MQTT topic etc. 

Possibly establish connection to Internet before configuring the Backend and report if backend can be connected to?

**Comment by ojousima** [comment]
Moving this to 1.7

**Comment by markoaamunkajo** [comment]
I was stuck with "Check" button in validation on one round and now I cannot reproduce this issue. I will try again to see if it happens, this thing is very elusive.

**Comment by TheSomeMan** [comment]
> I was stuck with "Check" button in validation on one round and now I cannot reproduce this issue. I will try again to see if it happens, this thing is very elusive.

Maybe there were some problems with the network or the server connection failed?
Also, if you modify settings for several targets (HTTP, MQTT, statistics), then all of them will be checked. If one of them will not pass validation, then "Check" button remains.
Could you try to enter an invalid URL, port, username, password to check that validation handles such problems?

**Comment by markoaamunkajo** [comment]
@TheSomeMan these locations for me are not making checks.

<img width="757" alt="NTP_time" src="https://user-images.githubusercontent.com/50437378/220273890-09d2a02a-c54c-4e9b-9184-b06a3d9dd66d.png">
<img width="691" alt="MQTT_topic" src="https://user-images.githubusercontent.com/50437378/220273910-188fd945-24b1-493d-b91f-540d50b6d60f.png">
<img width="667" alt="MQTT_port" src="https://user-images.githubusercontent.com/50437378/220273920-e830ec73-48a8-4499-ac45-0e9f6705ee48.png">
<img width="753" alt="config_server" src="https://user-images.githubusercontent.com/50437378/220273924-8f5dbdc7-4787-477b-9dce-33cfbf466ff2.png">
<img width="775" alt="fw_update" src="https://user-images.githubusercontent.com/50437378/220273928-6a43bd37-5cdd-4baa-9e48-1db3ac0e1a97.png">

**Comment by TheSomeMan** [comment]
@markoaamunkajo  Validation check for time servers is not yet supported because communication with them is done by ESP-IDF and there is no API to get the status of time synchronisation for each server. I added a separate task for this: #697.

For the automatic configuration download, your HTTP server should be working and should have "gw_cfg.json" file at the URL provided.

For the firmware update, the URL provided should contain three files: ruuvi_gateway_esp.bin, fatfw_gwui.bin and fatfs_nrf52.bin.

The validation check fails if the files are missing. You can check the logs to see what happened.

**Comment by markoaamunkajo** [comment]
Rechecked automatic config download, works
Rechecked fw update URL, works

This is QA passed
